Controllers films users
lazarx77/java-filmorate pull request #2
Opened 2024-06-27 14:40 UTC by lazarx77

Первая итерация проекта в соответствии с ТЗ спринта 10.

2024-06-28 15:54 UTC, kriwsha requested changes

2024-06-28 15:54 UTC, kriwsha commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                    films.put(updatedFilm.getId(), oldFilm);
Здесь нет необходимости сначала удалять объект из мапы, а потом возвращать. Вам необходимо провести ряд проверок, а затем решать, что делать с объектом фильма.

2024-06-28 15:54 UTC, kriwsha commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            if (updatedFilm.getDuration() == null) {
Я бы рекомендовал вынести проверки в отдельный утильный класс, чтобы контроллер был более лаконичный

2024-06-28 15:54 UTC, kriwsha commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    Map<Long, Film> films = new HashMap<>();
Не забывайте про модификаторы доступа

2024-06-28 15:54 UTC, kriwsha commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +                    users.put(updatedUser.getId(), oldUser);
В этом контроллере те же советы, что и для фильмов

2024-06-28 15:54 UTC, kriwsha commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTests.java
> +    private static Validator validator;
Можно оставить нестатичным

2024-06-28 15:54 UTC, kriwsha commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTests.java
> +    private Film film;
Каждый тест должен быть независимым, поэтому не должно существовать объектов, которые бы использовались в разных тестах

2024-06-28 15:54 UTC, kriwsha commented on src/test/java/ru/yandex/practicum/filmorate/UserControllerTests.java
> +    private static Validator validator;
Те же советы, что и для фильмов

2024-06-28 18:40 UTC, lazarx77 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                    films.put(updatedFilm.getId(), oldFilm);
В этом методе я проверяю на потенциальное создание дубликатов при обновлении. Вместо удаления я теперь сделал проверку на не равенство обновленной и старой версии, и если они не равны, затем идет проверка по всей таблице в поисках потенциальных дубликатов. Сравнение выполнено через сравнение объектов, так как @EqualsAndHashCode(of = {"name", "releaseDate"})

2024-06-28 18:40 UTC, lazarx77 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            if (updatedFilm.getDuration() == null) {
Создал утилитарный класс для валидации

2024-06-28 18:40 UTC, lazarx77 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    Map<Long, Film> films = new HashMap<>();
Исправил.

2024-06-28 18:40 UTC, lazarx77 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +                    users.put(updatedUser.getId(), oldUser);
Исправил.

2024-06-28 18:40 UTC, lazarx77 commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTests.java
> +    private static Validator validator;
Перенес validator в BeforeEach - void, убрал static

2024-06-28 18:40 UTC, lazarx77 commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTests.java
> +    private Film film;
поле film инициализируется в BeforeEach, каждый раз перед каждым тестом создается новый объект film = new Film

2024-06-28 18:40 UTC, lazarx77 commented on src/test/java/ru/yandex/practicum/filmorate/UserControllerTests.java
> +    private static Validator validator;
Исправил.

2024-06-29 20:03 UTC, kriwsha approved these changes

2024-06-30 01:47 UTC, merged