Add friends and likes
lazarx77/java-filmorate pull request #3
Opened 2024-07-11 10:04 UTC by lazarx77

Доработка функционала в соответствии с ТЗ 11 спринта.

2024-07-12 11:26 UTC, kriwsha requested changes

2024-07-12 11:26 UTC, kriwsha commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> + * FilmService.
Конечно, хорошо, когда есть документирующие комментарии. Но повторять название класса - плохая практика. Здесь я бы описал как "Сервис для работы с объектами фильмов". Да, это понятно из названия класса, но при автоматизированном сборе документации это будет более грамотно.

2024-07-12 11:26 UTC, kriwsha commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public void addLike(Long filmId, Long userId) {
Было бы здорово добавить документацию и на публичные методы с описанием входящих параметров и результата. Так работа будет выглядеть более профессионально

2024-07-12 11:26 UTC, kriwsha commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        // Находим пользователя по userId, если не найден, выбрасываем исключение
Бытует мнение, что если вы комментируете внутри метода, то следует этот метод декомпозировать. Здесь, как мне кажется, это не нужно. В чем суть документирования. Когда какой-то разработчик видит впервые код и ему нужно что-то исправить, то ему нужно провалиться до какого-то определенного уровня (н-р, метода), чтобы затем полностью изучить метод и сделать корректное исправление)

2024-07-12 11:26 UTC, kriwsha commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    Collection<Film> getAll();
Есть еще один способ документирования - это документирование интерфейсов, в то время как в реализующих его наследниках на методы ставится вот такой комментарий:
```
/**
* {@inheritDoc}
*/
```
В некоторых средах разработки (н-р, IDEA) это подтягивается при вызове документации по методу

2024-07-12 11:26 UTC, kriwsha commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTests.java
> +//    @Test
Не оставляйте закомментированные куски кода. Гит все помнит, поэтому можно смело удалять

2024-07-12 19:11 UTC, lazarx77 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> + * FilmService.
Сделал подробные описания для всех классов

2024-07-12 19:11 UTC, lazarx77 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public void addLike(Long filmId, Long userId) {
Потратил много времени на изучение документирования комментариев, а затем на их написание. Надеюсь, что все получилось правильно.

2024-07-12 19:11 UTC, lazarx77 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        // Находим пользователя по userId, если не найден, выбрасываем исключение
Пробежался по всему коду, убрал комментарии внутри методов (кроме одного пояснения)

2024-07-12 19:12 UTC, lazarx77 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    Collection<Film> getAll();
Прописал, надеюсь, правильно:-)

2024-07-12 19:12 UTC, lazarx77 commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTests.java
> +//    @Test
Оставил по невнимательности. Переделал тест с обновленной логикой

2024-07-13 17:39 UTC, kriwsha approved these changes

2024-07-13 17:48 UTC, merged