Add database
lazarx77/java-filmorate pull request #8
Opened 2024-08-06 12:36 UTC by lazarx77

Доработка функционала в соответствии с ТЗ 12 спринта.

2024-08-07 09:32 UTC, kriwsha requested changes

2024-08-07 09:32 UTC, kriwsha commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmDbStorage filmDbStorage;
Следует избегать ситуации, когда контроллер и хранилище связаны друг с другом. Лучше, чтобы между ними был сервисный слой. Представьте, вам потребуется изменить хранилище, где будет другой способ взаимодействия с базой данных. Тогда вам придется вносить изменения в контроллеры. А если вам придется поддерживать две версии, то это будет очень сложной задачей. В случае, если между контроллером и хранилищем будет еще класс сервис, который будет проксировать запросы, вам при смене хранилище достаточно будет подменить один сервис другим за счет слабой связности приложения. И поддерживать две версии всего приложения не придется - все будет зависеть от конфигураций, которыми вы будете управлять

2024-08-07 09:32 UTC, kriwsha commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +    private final GenreDbService genreService;
Здесь тоже следует между контроллером и хранением создать сервис, который будет проксировать запросы

2024-08-07 09:32 UTC, kriwsha commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaController.java
> +    private final MpaDbService mpaService;
И здесь

2024-08-07 13:04 UTC, lazarx77 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmDbStorage filmDbStorage;
Создал сервисы для всех хранилищ, часть логики перенес в методы сервисов, в том числе логирование, соответственно, методы в хранилищах, где возможно, упростил. Также вынес в сервисы валидации часть проверок из хранилищ.

2024-08-07 13:04 UTC, lazarx77 commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +    private final GenreDbService genreService;
Поправил.

2024-08-07 13:05 UTC, lazarx77 commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaController.java
> +    private final MpaDbService mpaService;
Поправил.

2024-08-08 14:31 UTC, kriwsha approved these changes

2024-08-08 16:26 UTC, merged